(ns katas-clj.roman-numerals-test
  (:require [clojure.test :refer :all]
            [clojure.test.tap :refer :all]
            [katas-clj.roman-numerals :refer :all]))


(deftest roman-test
  (are [input expected] (= expected (roman input))
                        0      ""
                        1      "I"
                        2      "II"
                        3      "III"
                        4      "IV"
                        5      "V"
                        6      "VI"
                        7      "VII"
                        8      "VIII"
                        9      "IX"
                        10     "X"
                        11     "XI"
                        12     "XII"
                        13     "XIII"
                        14     "XIV"
                        15     "XV"
                        16     "XVI"
                        17     "XVII"
                        18     "XVIII"
                        19     "XIX"
                        20     "XX"
                        21     "XXI"
                        28     "XXVIII"
                        29     "XXIX"
                        30     "XXX"
                        37     "XXXVII"
                        39     "XXXIX"
                        40     "XL"
                        48     "XLVIII"
                        49     "XLIX"
                        50     "L"
                        51     "LI"
                        58     "LVIII"
                        59     "LIX"
                        70     "LXX"
                        78     "LXXVIII"
                        89     "LXXXIX"
                        90     "XC"
                        98     "XCVIII"
                        99     "XCIX"
                        100    "C"
                        101    "CI"
                        120    "CXX"
                        138    "CXXXVIII"
                        139    "CXXXIX"
                        140    "CXL"
                        150    "CL"
                        188    "CLXXXVIII"
                        189    "CLXXXIX"
                        190    "CXC"
                        193    "CXCIII"
                        194    "CXCIV"
                        195    "CXCV"
                        198    "CXCVIII"
                        199    "CXCIX"
                        200    "CC"
                        230    "CCXXX"
                        288    "CCLXXXVIII"
                        300    "CCC"
                        322    "CCCXXII"
                        349    "CCCXLIX"
                        389    "CCCLXXXIX"
                        390    "CCCXC"
                        399    "CCCXCIX"
                        400    "CD"
                        489    "CDLXXXIX"
                        500    "D"
                        501    "DI"
                        888    "DCCCLXXXVIII"
                        889    "DCCCLXXXIX"
                        890    "DCCCXC"
                        899    "DCCCXCIX"
                        900    "CM"
                        989    "CMLXXXIX"
                        990    "CMXC"
                        998    "CMXCVIII"
                        999    "CMXCIX"
                        1000   "M"
                        1100   "MC"
                        1776   "MDCCLXXVI"
                        1888   "MDCCCLXXXVIII"
                        2000   "MM"
                        2888   "MMDCCCLXXXVIII"
                        3000   "MMM"
                        3888   "MMMDCCCLXXXVIII"
                        3889   "MMMDCCCLXXXIX"
                        3998   "MMMCMXCVIII"
                        3900   "MMMCM"
                        4000   "MMMM"
                        4999   "MMMMCMXCIX"
                        ))


(run-tests)

